Freeze pytest version
Newer versions of pytest cause issues for flexmock, causing failures in
tests CI such as:

tests/utils/test_yaml.py:11: in <module>
    from flexmock import flexmock
/usr/lib/python3.10/site-packages/flexmock/__init__.py:2: in <module>
    from flexmock import _integrations  # pylint: disable=unused-import
/usr/lib/python3.10/site-packages/flexmock/_integrations.py:101: in <module>
    saved_pytest = runner.call_runtest_hook
E   AttributeError: module '_pytest.runner' has no attribute 'call_runtest_hook'

Signed-off-by: mkosiarc <mkosiarc@redhat.com>