Use architecture as destination name in argparse
This name is used in the rest of the code. Before it wasn't possible to
set architecture and following exception was raised:

  ...
  File ".../osbs/osbs/build/spec.py", line 70, in validate
    raise OsbsValidationException("param '%s' is not valid: None is not allowed" % param.name)
osbs.exceptions.OsbsValidationException: param 'architecture' is not valid: None is not allowed