BuildResponse: avoid traceback in get_error_reason
A missing annotation would result in a traceback:
...
File /usr/lib/python2.6/site-packages/osbs/build/build_response.py, line 128, in get_error_reason
    metadata_dict = json.loads(str_metadata)
  File /usr/lib64/python2.6/json/__init__.py, line 307, in loads
    return _default_decoder.decode(s)
  File /usr/lib64/python2.6/json/decoder.py, line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

Signed-off-by: Tim Waugh <twaugh@redhat.com>