Fix yaml exception wrapping
Previously the traceback could look like this:
```
Traceback (most recent call last):
[...]
OsbsException: ScannerError()

Original traceback (most recent call last):
[...]
  File "/usr/lib64/python2.6/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not found expected ':'", self.get_mark())
ScannerError()
```

This is because repr() for a yaml exception only reveals 'ScannerError()'
whereas str() reveals the line and column.

Use str() on the underlying exception when str() is called on the
wrapping exception.

Signed-off-by: Tim Waugh <twaugh@redhat.com>